version: '3'
services:
  mn-groovy-on:
    build: .
    environment:
      PYROSCOPE_ENABLED: "true"
      PYROSCOPE_URL: "<URL here>"
      PYROSCOPE_USER: "<USER here>"
      PYROSCOPE_PASSWORD: "<PASSWORD here>"
    ports:
      - 8086:8080
    depends_on:
      - mysql
    links:
      - mysql
  mn-groovy-off:
    build: .
    environment:
      PYROSCOPE_ENABLED: "false"
    ports:
      - 8087:8080
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:8
    container_name: mysql8
    hostname: mysql-int
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0p9o8i7u
      MYSQL_DATABASE: test
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-3:/var/lib/mysql
      - ./data/test_db.sql:/docker-entrypoint-initdb.d/test_db.sql
    cap_add:
      - SYS_NICE
volumes:
  mysql-data-3:
