micronaut:
  application:
    name: hello
  executors:
    dataaccess:
      type: fixed
      nThreads: 75
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    pooled: true
    url: jdbc:mysql://mysql-int:3306/test
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 0p9o8i7u
    dbCreate: auto
    logSql: false
    properties:
      maxActive: 50
      maxIdle: 50
      minIdle: 5
      initialSize: 5
      minEvictableIdleTimeMillis: 60000
      timeBetweenEvictionRunsMillis: 60000
      maxWait: 100000
      numTestsPerEvictionRun: 3
      testOnBorrow: false /*for perf test*/
      testOnReturn: false /*for perf test*/
      testWhileIdle: true
      validationQuery: /* ping */
hibernate:
  hbm2ddl:
    auto: update
  dialect: org.hibernate.dialect.MySQL8Dialect
pyroscope:
  enabled: ${PYROSCOPE_ENABLED:false}
  server: ${PYROSCOPE_URL:`http://localhost:4040`}
  username: ${PYROSCOPE_USER:``}
  password: ${PYROSCOPE_PASSWORD:``}
jpa:
  default:
    entity-scan:
      packages:
        - 'com.sample.domain'
    properties:
      hibernate:
        show-sql: true
        hbm2ddl:
          auto: update
